core/accounts/urls.py
from django.urls import path
from .views import UserProfileView, EditProfile

app_name="accounts"

urlpatterns = [
    path('<username>/', UserProfileView, name="profile"),
    path('profile/edit', EditProfile, name="edit-profile"),
    
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('users/', include('accounts.urls', namespace='users')),

    path('social/', include('social.urls', namespace='social')), 

    path('', HomeView.as_view(), name="home"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/templates/users/base.html
{% load static %}
{% load tailwind_tags %}
{% load tailwind_filters %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon icon-->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon2.png' %}">

    <!-- Tailwind -->
    {% tailwind_css %}

    <!-- AlpineJS -->
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js" defer></script>

    <!-- Extras CSS/JS -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

    {% block extra_head %}{% endblock extra_head %}
    <title>{% block title %}{% endblock title %}</title>
    <script src="https://pagecdn.io/lib/jquery/3.2.1/jquery.min.js"></script>
</head>
<body class="bg-gray-100 dark:bg-dark-main flex justify-center ">
    
    <!-- NAVBAR -->
    {% block navbar %}{% endblock navbar %}

    <!--CONTENT-->
     <div class="flex w-full justify-center h-screen ">

        {% block messages %}{% include 'messages.html' %}{% endblock messages %}
        {% block content %}{% endblock content %}

     </div>

    <!--RIGHT SIDEBAR-->

    <!-- FOOTER -->
    <!-- Scripts -->
    {% block javascript %}{% endblock javascript %}


</body>
</html>

core/templates/users/edit.html
{% extends 'base.html' %}

{% load static %}

{% load tailwind_filters %}

{% block title %}{{user.username}} Edit Profile{% endblock title %}

{% block navbar %}
{% include 'components/navbar.html' %}
{% endblock navbar %}

{% block left_sidebar %}
{% comment %} {% include 'components/sidebars/left/users/sidebar.html' %} {% endcomment %}
{% endblock left_sidebar %}

{% block content %}
<form class="form-horizontal dark:text-dark-txt" method="post"  enctype="multipart/form-data">
{% csrf_token %}
<div class="mt-1 sm:mt-0 sm:col-span-2">
      <img class="h-28 w-full bg-cover" src="{{user.profile.banner.url}}" alt="{{profile.user.username}} Banner">

      <div class="max-w-lg flex justify-center px-6 pt-5 pb-6 border-2 dark:border-dark-third border-gray-300 border-dashed rounded-md">
        {{form.banner}}
        <div class="space-y-1 text-center">
          <div class="flex text-sm text-gray-600">
            
          </div>
        </div>
      </div>

      <!--Profile Picture-->
        <div class="mt-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-center sm:border-t dark:border-dark-third  border-gray-200 sm:pt-5">
        <label for="photo" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
            Photo
        </label>
        <div class="mt-1 sm:mt-0 sm:col-span-2">
            <div class="flex items-center">
            <span class="mr-4 h-18 w-18 rounded-full overflow-hidden dark:bg-dark-third bg-gray-100">
                <img src="{{user.profile.picture.url}}" alt="">
            </span>
            {{form.picture}}
            </div>
        </div>
        </div>

        <div class="mt-4">
        <label for="first name" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
        First Name
        </label>
        {{form.first_name}}
        </div>
        <label for="last name" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
            Last Name
        </label>
        {{form.last_name}}

        <label for="bio" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
            Bio
        </label>
        {{form.bio}}

        <label for="city" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
        Location: City, Country
        </label>
        {{form.location}}

        <label for="birthday" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
        Date of Birth: yyyy-mm-dd
        </label>
        {{form.birthday}}

        <label for="url" class="block text-sm font-medium dark:text-dark-txt text-gray-700">
        Website URL
        </label>
        {{form.url}}
        </div>

         <div class="control-group">
            <div class="controls">
            <a href="{% url 'users:profile' username=user.username %}" class="mt-4 inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-indigo-700 dark:bg-dark-second bg-indigo-100 dark:hover:bg-dark-third hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-indigo-500">
            Return to Profile </a>
            <button type="submit" class="mt-4 inline-flex float-right items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-indigo-700 dark:bg-dark-third bg-indigo-100 dark:hover:bg-dark-third hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-indigo-500">
            Update</button>
            </div>
        </div>

    </div>
</form>
{% endblock content %}